# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.ts","*.tsx","*.scss","*.json"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
